# dc before bc because it depends on dc.o
SUBDIR = apply awk basename dc bc biff cal calendar cmp colrm col column comm \
	 cut dirname du diff3 diff env expand false file fmt fold getopt grep head \
	 hexdump id indent join jot lam lndir logger logname look mktemp nice \
	 nl nohup paste patch printenv printf readlink renice rev rs sed shar \
	 sort split stat tee time touch tr true tsort tty uname unexpand uniq unvis \
	 uudecode uuencode vis wc what which xinstall hexdump cu newsyslog sdiff
SKIPDIR = file cu
include bsd.subdir.mk
