TOPDIR?=..
SUBDIR=	apply awk basename bc biff cal calendar cmp colrm col column comm \
	cut dc dirname du diff3 diff encrypt env expand false file fmt fold \
	ftp getopt grep head hexdump id indent join jot lam lndir logger \
	logname look mktemp nice nl nohup paste patch printenv printf readlink \
	renice rev rs sed shar sort spell split stat tee time touch tr true \
	tsort tty ul units uname unexpand uniq unvis uudecode uuencode vis wc \
	what which xinstall htpasswd cu newsyslog sdiff banner cap_mkdb signify \
	unifdef whois xargs csplit
SKIPDIR=file ftp cu
include ${.TOPDIR}/mk/bsd.subdir.mk
