#	$OpenBSD: Makefile,v 1.9 2013/04/15 06:25:18 deraadt Exp $

.TOPDIR?=../..

PROG=	mtree
#CFLAGS+=-DDEBUG
MAN=	mtree.8
SRCS=	compare.c crc.c create.c misc.c mtree.c spec.c verify.c

include ${.TOPDIR}/mk/bsd.prog.mk
